---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1m3cj7a2auwuanpqtugv29834mmlwqzcd43tjnczqwts3k9tgv35q86xkl7"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1m3cj7a2auwuanpqtugv29834mmlwqzcd43tjnczqwts3k9tgv35q86xkl7"
