---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 36.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 30m
  targetNamespace: network
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  releaseName: traefik
  values:
    deployment:
      replicas: 1
    service:
      annotations:
        lbipam.cilium.io/ips: "192.168.1.12"
    ingressClass:
      isDefaultClass: false
      name: "traefik"
    gateway:
      enabled: false
    gatewayClass:
      enabled: false
    ingressRoute:
      dashboard:
        enabled: true

    ports:
      web:
        port: 8000
      websecure:
        asDefault: true
        port: 8443

    persistence:
      enabled: true
      storageClass: longhorn
      size: 256Mi
    
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
