apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:LOUYSMhVUHyCaboq7DICXiGBQo7l2uDCkt58YurRqLWdBiEH,iv:u69a3m7MPnEjvey+bPyQOaohyb6E5nFwizG+jqy+uZQ=,tag:jQa2vTgx5UchiWrAKriv2A==,type:str]
    credentials.json: ENC[AES256_GCM,data:enHxNTRvoXYgS8Zn3+H7ijXmxVbP8dRUq/YE3GDaO7GTgMOjbOPsth2O7bLPMe0xwhl64PbGos0XQ6U7nv3Z/aTQWzcbg+ZRzUiMPVUqGiQFfqgRUgBP7epBzM6ECyaJcpd10fLFz+2tgGbmds6giOl9kUznoTcKuIpQrs6ETOFad+H4Rof/L3tx3dJkQsKV321g6K3M24bVsYkNClS6whVcKRhnZ60MG/A3WQLStw==,iv:eUiE77g5wtYDrHSZh4Cp9CG0VXM4o7ItJ+YHraR1c+E=,tag:VnNqHRbu+i6TQ7TuRZQ/iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3cj7a2auwuanpqtugv29834mmlwqzcd43tjnczqwts3k9tgv35q86xkl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeE1EUjI2Yk9aNUtrM0dm
            Tldzd1dLcnZ3VDQrR3JmaFA5a1lUL2ZiMVEwCitFTUdKd28zNktSOFJOTHA3cXE1
            bldKYW5GTEVZQklkQzF5ejl1L3MzSGMKLS0tIHJ5WEpTdFJ2R0s1RHphdnJNWjg0
            bnJiaU5HclVRcEtHWEczN2JVYmJBQ1kKOeQemwLm9U54x4DclOS7tXZU5lg34kH6
            zI9J4ZnMIQoMYMWlhTrCZIeCHhElCIwir2U7paK/1/uFqNIHSN0hbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T15:05:56Z"
    mac: ENC[AES256_GCM,data:SlYTPhoekbiDmGPxJ1qEu8/9dexrfjFkLYca1VTmCgiWGV8YPA4jq1ZzvcS2eeuIoRM3sDvOqv3lmuPvEEMJPiRhooKCcfNzFgktsw8Vppf64L1w8qsucRiPqXa6QKIQmXgaSFFvErR1oxRmTZi4/Pkvmf03Ix+RERzuzpwodkU=,iv:+HgmDg2J8WkkYMLgnCoi/oEWnmZVziMRH8K/NtFCJLA=,tag:diUJGXwgJZCqm497ThZFDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
