---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.6.0
  interval: 24h0m0s
  releaseName: bazarr
  targetNamespace: default
  values:
    global:
      fullnameOverride: bazarr
    controllers:
      main:
        enabled: true
        containers:
          main:
            nameOverride: bazarr
            image:
              repository: linuxserver/bazarr
              tag: 1.5.1
            env:
              TZ: America/Chicago
              PGID: 1000
              PUID: 1000
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: 6767
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: bazarr.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
        tls:
          - secretName: bazarr-tls
            hosts:
              - bazarr.internal.${SECRET_DOMAIN}

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        size: 1Gi
        accessMode: ReadWriteOnce
      movies:
        enabled: true
        type: nfs
        server: 192.168.1.171
        path: /mnt/storage-pool/media/movies
      tv:
        enabled: true
        type: nfs
        server: 192.168.1.171
        path: /mnt/storage-pool/media/tv
