apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2H70FXxZcV0mrBma9KDNTlfL5Ixl/5DeOtWoavnh9Cu71lYAjSfSAw==,iv:XKJkbsZfZqBgX/HN9xgyKo3gbMHyre76TXSeuHkdtnE=,tag:L8AkvVWTDAwYynxoOSTTPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3cj7a2auwuanpqtugv29834mmlwqzcd43tjnczqwts3k9tgv35q86xkl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVHJ0ai9scGM4QTU1bDla
            WDM2TE5wWWM2alYvYUpvdFM2SCtqMVo2Y2tvCjQzZmV0NEZoS1dmYkswOW42d1h0
            T01Ya01nRlZRV1k5R1htZFpTWVZSZGcKLS0tIFhrTmlWQ0lDS3FDSlVjcXdORzVs
            YkY2ZmVxZXlVUGdYWDhjSE5wdzdDZ0EK9Jkez6WmgtwMow+ykPAKO0Z9hzWVc/SN
            WbR3ZV14lkwbdaWOu4D+OMSn7shNBhDN8rwvran887Pf3MDZzWCzKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T20:36:17Z"
    mac: ENC[AES256_GCM,data:X0+bjq2GqyuCZaAfPUwYX6CxHYj5fPxcvRqKo6eexsyAy+A+Yx8Cumx7hB4KbxSRDOESvsSdg8CmtEv4Ptx1PWUlax35zBUu8qXpm2QIYazdurs/LXvjW+IBYp4G8IfX+IeQwoIaGy1hvR0gA15FYaOJg7Twi+dlA5IgjJ8hivQ=,iv:sVqlsQ3qzGnuU8JoimIJb21dVUwcti4AyahPlNFtfr0=,tag:WvCj6BJnLDneQ2XcdCfQCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
