apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: default
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:K1vm+TQE29RkB4nsiGEN+yVkqvoWYuZUrSzOMfVb0QMHVWn5NxoVAxTyd5cHSm9rUth0P1mjR88qHxvhx7d4p1Gf5DKwR+6anIlgvN8govijNUg+9Rt+cNCM/ONjqvE10h6FbVVr69G08Ec+a1/V0q8+wckCt71MOQ==,iv:mcYkII3GFtned/fF7S4uLFd4ijDduqQ9MiPPH4wtQvM=,tag:jbXSG9RwUsVf58xwrqVOzw==,type:str]
sops:
    age:
        - recipient: age1m3cj7a2auwuanpqtugv29834mmlwqzcd43tjnczqwts3k9tgv35q86xkl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRjNFWGppMTdtRVJSTXph
            bFRKcHlXbTRRVGdNS1ZPQ095M1phZzU0a0RJCkNhMUFFWnIrMTJmZDVvcnpMdzU2
            TzJVajlVOGZrYkdrOG0zd0VpLzAzdk0KLS0tIGVibWtHMFZOdHdSRnYyTDczWmZV
            T0JGREtsUjlNYUU2ekJXQlg2RW1PUzgKJJzzAxAN1Nh+H8bxDL53G086cUZk1Fy7
            ablr7MpzYr/y/A6W8k7mVQkrjbNsPmsL9thpmbOYnGe8PRn6UKze7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T17:21:03Z"
    mac: ENC[AES256_GCM,data:zLa9SsIlX+QAcgLCh7Wr6CQmaS9KeeNhWyGRxjD3AxVrAgRwW78fpSKp+Soerr9G6splvxeDj3/pTpYgyABeYGq/It18Xrc/v+vvFS65N8/JqPs69VCIHLiawIL8kk6I/+KkOfdiWGDpJC2ox5jxLIE0HBf6nxrkYFL5w41VK6k=,iv:Vtn2WNsQy22gm7TrBxjxwnSeMak4SXF6sNnx87ayeLs=,tag:Omm2hAleEqWsidHHmP42Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
