---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-ssd
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
#  mountOptions:
#    - nolock
#    - nfsvers=4.1
#    - noacl
#    - nocto
#    - noatime
#    - nodiratime
#    - rsize=32768
#    - wsize=32768
  nfs:
    path: /mnt/storage-pool/media
    server: 192.168.1.171
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc-ssd
  namespace: default
spec:
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteMany
  volumeName: media-pv-ssd
  storageClassName: ""
