---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-ssd
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/storage-pool/media
    server: 192.168.1.171
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc-ssd
  namespace: default
spec:
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteMany
  volumeName: media-pv-ssd
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv-ssd
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/storage-pool/downloads
    server: 192.168.1.171
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc-ssd
  namespace: default
spec:
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  volumeName: downloads-pv-ssd
  storageClassName: ""
