---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tubearchivist-stable
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.4.0
  driftDetection:
    mode: enabled
  interval: 1h0m0s
  releaseName: tubearchivist-stable
  targetNamespace: default
  maxHistory: 2
  values:
    global:
      fullnameOverride: tubearchivist-stable
    controllers:
      main:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          main:
            image:
              repository: bbilly1/tubearchivist
              tag: v0.4.13
            env:
              - name: TZ
                value: America/Chicago
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: TA_HOST
                value: tubearchivist.internal.${SECRET_DOMAIN}
              - name: REDIS_CON
                value: redis://tubearchivist-stable-redis:6379
              - name: REDIS_HOST
                value: tubearchivist-stable-redis
              - name: ES_URL
                value: http://tubearchivist-stable-elasticsearch:9200
            envFrom:
              - secret: ta-stable-creds
      elasticsearch:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          elasticsearch:
            image:
              repository: bbilly1/tubearchivist-es
              tag: latest
            env:
              - name: ES_JAVA_OPTS
                value: -Xms512m -Xmx512m
              - name: "discovery.type"
                value: single-node
              - name: "path.repo"
                value: /usr/share/elasticsearch/data/snapshot
              - name: "xpack.security.enabled"
                value: "true"
            envFrom:
              - secret: ta-stable-creds
            resources:
              limits:
                cpu: 1000m
                memory: 1024Mi
              requests:
                cpu: 500m
                memory: 512Mi
      redis:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          redis:
            image:
              repository: redis
              tag: latest
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            primary: true
            port: 8000
      elasticsearch:
        enabled: true
        controller: elasticsearch
        ports:
          http:
            enabled: true
            primary: true
            port: 9200
      redis:
        enabled: true
        controller: redis
        ports:
          tcp-redis:
            enabled: true
            primary: true
            port: 6379
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: tubearchivist.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: tubearchivist-stable-tls
            hosts:
              - tubearchivist.internal.${SECRET_DOMAIN}
    serviceMonitor:
      main:
        enabled: false
        serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      cache:
        enabled: true
        accessMode: ReadWriteMany
        storageClass: nfs-client-ssd
        size: 5Gi
      youtube:
        enabled: true
        existingClaim: media-pvc-ssd
        globalMounts:
          - path: /youtube
            subPath: youtube
      elasticsearch:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
        size: 5Gi
        advancedMounts:
          elasticsearch:
            elasticsearch:
              - path: "/usr/share/elasticsearch/data"
                readOnly: false
      redis:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
        size: 1Gi
        advancedMounts:
          redis:
            redis:
              - path: "/data"
                readOnly: false
