apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Vv4xKS/BHyNAb3wASfnIzzNC6c9SOGj2WOM4C4+zLa8=,iv:NjKvHOvbYeYEWzQjxaJwdHlYfPt6oAHFB5SSMMuPhtM=,tag:sxkZwBSaM2aOr94YgDASnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m3cj7a2auwuanpqtugv29834mmlwqzcd43tjnczqwts3k9tgv35q86xkl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YUMwUk4raThVdDczM0FF
            aUVqYVBOVmFFK3hqYVBwWlNDSldmYmZnTEVvCkpZSm1zS1d3VUdSRTRPM0RLNkow
            bExNNjVuWnVOSlpWUG4reC96UzlYMGsKLS0tIEpUSU40VWRBd0J3L2lRZXVJYVlL
            T2FhYmpoWGd5Y0VzVFpET1ZIQTlrNXcKhhhwhqB+m1b0TXJfUnAeQZcDlpEDRGaS
            7oEEz07Ty510gkDEM0xj+MmPYzWzny2WjSziLQ2NSWDq5Mzrc+zBSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T15:03:13Z"
    mac: ENC[AES256_GCM,data:pVrP95irg6cMD9OVr4/SGrAyX5mZV7JBfp0cnugzxD5PtkQ+c3seaxqG7ZDWPFgliOUrT7AbY+PzsdYH0O7YuVype4xuRRKN71myPg10MISCGNIacpNgrtz0f7g/1b32e/fW8Kr/x7WpEoYoUiD7SOfNz6bGaUkYMrBtC+aEulw=,iv:pcFEMwK9RXGPcNCNo7Vc547m/P8bo+2etonyile4NGc=,tag:skWdQD22pRLnjsLhxavABw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
